spring:
  threads:
    virtual:
      enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbhefesto
    username: postgres
    password: abcd1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        format_sql: true
         
joinfaces:
  primefaces:
    theme: saga
  faces:
    project-stage: Production

application-users:
  users-credentials:
    - username: admin
      password: admin
      authorities: ROLE_ADMIN
    - username: henrique.souza
      password: abcd1234
      authorities: ROLE_USER
